// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuranCompanion.Infrastructure.Persistence;

#nullable disable

namespace QuranCompanion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525231829_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuranCompanion.Domain.Import.ImportHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("import_type");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_code");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_import_histories");

                    b.HasIndex("SourceCode", "ImportType", "ContentHash")
                        .HasDatabaseName("ix_import_histories_source_type_hash");

                    b.ToTable("import_histories", "import");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.Surah", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameTransliteration")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_transliteration");

                    b.Property<string>("NameTurkish")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_turkish");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("RevelationPlace")
                        .HasColumnType("integer")
                        .HasColumnName("revelation_place");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("VerseCount")
                        .HasColumnType("integer")
                        .HasColumnName("verse_count");

                    b.HasKey("Id")
                        .HasName("pk_surahs");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_surahs_number");

                    b.ToTable("surahs", "quran");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.TranslationSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language_code");

                    b.Property<string>("LicenseInfo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("license_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_url");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_translation_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_translation_sources_code");

                    b.ToTable("translation_sources", "quran");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.Verse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_text");

                    b.Property<string>("ArabicTextClean")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_text_clean");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("GlobalVerseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("global_verse_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("JuzNumber")
                        .HasColumnType("integer")
                        .HasColumnName("juz_number");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<long>("SurahId")
                        .HasColumnType("bigint")
                        .HasColumnName("surah_id");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("integer")
                        .HasColumnName("surah_number");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("verse_number");

                    b.HasKey("Id")
                        .HasName("pk_verses");

                    b.HasIndex("GlobalVerseNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_verses_global_verse_number");

                    b.HasIndex("JuzNumber")
                        .HasDatabaseName("ix_verses_juz_number");

                    b.HasIndex("PageNumber")
                        .HasDatabaseName("ix_verses_page_number");

                    b.HasIndex("SurahId")
                        .HasDatabaseName("ix_verses_surah_id");

                    b.HasIndex("SurahNumber", "VerseNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_verses_surah_verse");

                    b.ToTable("verses", "quran");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.VerseTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("TranslationSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("translation_source_id");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<long>("VerseId")
                        .HasColumnType("bigint")
                        .HasColumnName("verse_id");

                    b.HasKey("Id")
                        .HasName("pk_verse_translations");

                    b.HasIndex("NormalizedText")
                        .HasDatabaseName("ix_verse_translations_normalized_text_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TranslationSourceId")
                        .HasDatabaseName("ix_verse_translations_source");

                    b.HasIndex("VerseId", "TranslationSourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_verse_translations_verse_source");

                    b.ToTable("verse_translations", "quran");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.Verse", b =>
                {
                    b.HasOne("QuranCompanion.Domain.Quran.Surah", "Surah")
                        .WithMany("Verses")
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verses_surahs_surah_id");

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.VerseTranslation", b =>
                {
                    b.HasOne("QuranCompanion.Domain.Quran.TranslationSource", "TranslationSource")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verse_translations_translation_sources_translation_source_id");

                    b.HasOne("QuranCompanion.Domain.Quran.Verse", "Verse")
                        .WithMany("Translations")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_translations_verses_verse_id");

                    b.Navigation("TranslationSource");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.Surah", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.TranslationSource", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QuranCompanion.Domain.Quran.Verse", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
